package com.spice.bean;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;

import com.spice.connection.DBConnection;

public class UssdInfoBean {
	public String dateConvert(String tempdate ) {
		String str[] = null;
		if(tempdate!=null){
			 str= tempdate.split("/");
		}
		String date = "";
		if(str!=null && str.length>0){
			date=str[2]+"-"+str[1]+"-"+str[0];
		}
		return date;
	}
	 public Map[] GetData(String startdate, String enddate) throws Exception {
		 ResultSet rs = null;
		 Connection conn = null;
		 Statement stmt = null;
		 String  sdate = dateConvert(startdate);
		 String  edate = dateConvert(enddate);
		 int total_sub_req_rec_15=0;
		 int total_sub_req_rec_5=0;
		 int total_sub_req_rec_2=0;
		 int total_sub_suc_15=0;
		 int total_sub_suc_5=0;
		 int total_sub_suc_2=0;
		 int total_resub_req_rec_15=0;
		 int total_resub_req_rec_5=0;
		 int total_resub_req_rec_2=0;
		 int total_resub_suc_15=0;
		 int total_resub_suc_5=0;
		 int total_resub_suc_2=0;
		 int total_sub_revenue=0;
		 int total_resub_revenue=0;
		 String query = "select * from ussd_info.tbl_ussd_info_mis_summary1  where date_time between '"+sdate+"' and '"+edate+"' order by date_time asc";
		 System.out.println("Select Query is --"+query);
		 Map[] s = null;
		 int length = 0;
		 
		 int i = 0;
		 try {
			 conn = DBConnection.getConnection();
			 stmt = conn.createStatement();
			 rs = stmt.executeQuery("select count(1) as cnt from ussd_info.tbl_ussd_info_mis_summary1  where date_time between '"+sdate+"' and '"+edate+"' ") ;
			 while(rs.next()) {
				 length = rs.getInt("cnt");
			 }
			 rs = null;
			 rs = stmt.executeQuery(query);
			 s = new HashMap[length];
			 while(rs.next()) {
				 s[i] = new HashMap();
				 total_sub_req_rec_15=rs.getInt("subscription_requests_received__15_afn_eq")+rs.getInt("subscription_requests_received__15_afn_ej")+rs.getInt("subscription_requests_received__15_afn_eh")+rs.getInt("subscription_requests_received__15_afn_ep")+rs.getInt("subscription_requests_received__15_afn_eb")+rs.getInt("subscription_requests_received__15_afn_ec")+rs.getInt("subscription_requests_received__15_afn_epu")+rs.getInt("subscription_requests_received__15_afn_es")+rs.getInt("subscription_requests_received__15_afn_eho")+rs.getInt("subscription_requests_received__15_afn_kk")+rs.getInt("subscription_requests_received__15_afn_nb")+rs.getInt("subscription_requests_received__15_afn_nh")+rs.getInt("subscription_requests_received__15_afn_nw")+rs.getInt("subscription_requests_received__15_afn_nwe")+rs.getInt("subscription_requests_received__15_afn_ns")+rs.getInt("subscription_requests_received__15_afn_nsh")+rs.getInt("subscription_requests_received__15_afn_fc")+rs.getInt("subscription_requests_received__15_afn_ff")+rs.getInt("subscription_requests_received__15_afn_fg")+rs.getInt("subscription_requests_received__15_afn_fgr");
				 total_sub_req_rec_5=rs.getInt("subscription_requests_received__5_afn_eq")+rs.getInt("subscription_requests_received__5_afn_ej")+rs.getInt("subscription_requests_received__5_afn_eh")+rs.getInt("subscription_requests_received__5_afn_ep")+rs.getInt("subscription_requests_received__5_afn_eb")+rs.getInt("subscription_requests_received__5_afn_ec")+rs.getInt("subscription_requests_received__5_afn_epu")+rs.getInt("subscription_requests_received__5_afn_es")+rs.getInt("subscription_requests_received__5_afn_eho")+rs.getInt("subscription_requests_received__5_afn_kk")+rs.getInt("subscription_requests_received__5_afn_nb")+rs.getInt("subscription_requests_received__5_afn_nh")+rs.getInt("subscription_requests_received__5_afn_nw")+rs.getInt("subscription_requests_received__5_afn_nwe")+rs.getInt("subscription_requests_received__5_afn_ns")+rs.getInt("subscription_requests_received__5_afn_nsh")+rs.getInt("subscription_requests_received__5_afn_fc")+rs.getInt("subscription_requests_received__5_afn_ff")+rs.getInt("subscription_requests_received__5_afn_fg")+rs.getInt("subscription_requests_received__5_afn_fgr");
				 total_sub_req_rec_2=rs.getInt("subscription_requests_received__2_afn_eq")+rs.getInt("subscription_requests_received__2_afn_ej")+rs.getInt("subscription_requests_received__2_afn_eh")+rs.getInt("subscription_requests_received__2_afn_ep")+rs.getInt("subscription_requests_received__2_afn_eb")+rs.getInt("subscription_requests_received__2_afn_ec")+rs.getInt("subscription_requests_received__2_afn_epu")+rs.getInt("subscription_requests_received__2_afn_es")+rs.getInt("subscription_requests_received__2_afn_eho")+rs.getInt("subscription_requests_received__2_afn_kk")+rs.getInt("subscription_requests_received__2_afn_nb")+rs.getInt("subscription_requests_received__2_afn_nh")+rs.getInt("subscription_requests_received__2_afn_nw")+rs.getInt("subscription_requests_received__2_afn_nwe")+rs.getInt("subscription_requests_received__2_afn_ns")+rs.getInt("subscription_requests_received__2_afn_nsh")+rs.getInt("subscription_requests_received__2_afn_fc")+rs.getInt("subscription_requests_received__2_afn_ff")+rs.getInt("subscription_requests_received__2_afn_fg")+rs.getInt("subscription_requests_received__2_afn_fgr");
				 total_sub_suc_15=rs.getInt("successful_subscriptions__15_afn_eq")+rs.getInt("successful_subscriptions__15_afn_ej")+rs.getInt("successful_subscriptions__15_afn_eh")+rs.getInt("successful_subscriptions__15_afn_ep")+rs.getInt("successful_subscriptions__15_afn_eb")+rs.getInt("successful_subscriptions__15_afn_ec")+rs.getInt("successful_subscriptions__15_afn_epu")+rs.getInt("successful_subscriptions__15_afn_es")+rs.getInt("successful_subscriptions__15_afn_eho")+rs.getInt("successful_subscriptions__15_afn_kk")+rs.getInt("successful_subscriptions__15_afn_nb")+rs.getInt("successful_subscriptions__15_afn_nh")+rs.getInt("successful_subscriptions__15_afn_nw")+rs.getInt("successful_subscriptions__15_afn_nwe")+rs.getInt("successful_subscriptions__15_afn_ns")+rs.getInt("successful_subscriptions__15_afn_nsh")+rs.getInt("successful_subscriptions__15_afn_fc")+rs.getInt("successful_subscriptions__15_afn_ff")+rs.getInt("successful_subscriptions__15_afn_fg")+rs.getInt("successful_subscriptions__15_afn_fgr");
				 total_sub_suc_5=rs.getInt("successful_subscriptions__5_afn_eq")+rs.getInt("successful_subscriptions__5_afn_ej")+rs.getInt("successful_subscriptions__5_afn_eh")+rs.getInt("successful_subscriptions__5_afn_ep")+rs.getInt("successful_subscriptions__5_afn_eb")+rs.getInt("successful_subscriptions__5_afn_ec")+rs.getInt("successful_subscriptions__5_afn_epu")+rs.getInt("successful_subscriptions__5_afn_es")+rs.getInt("successful_subscriptions__5_afn_eho")+rs.getInt("successful_subscriptions__5_afn_kk")+rs.getInt("successful_subscriptions__5_afn_nb")+rs.getInt("successful_subscriptions__5_afn_nh")+rs.getInt("successful_subscriptions__5_afn_nw")+rs.getInt("successful_subscriptions__5_afn_nwe")+rs.getInt("successful_subscriptions__5_afn_ns")+rs.getInt("successful_subscriptions__5_afn_nsh")+rs.getInt("successful_subscriptions__5_afn_fc")+rs.getInt("successful_subscriptions__5_afn_ff")+rs.getInt("successful_subscriptions__5_afn_fg")+rs.getInt("successful_subscriptions__5_afn_fgr");
				 total_sub_suc_2=rs.getInt("successful_subscriptions__2_afn_eq")+rs.getInt("successful_subscriptions__2_afn_ej")+rs.getInt("successful_subscriptions__2_afn_eh")+rs.getInt("successful_subscriptions__2_afn_ep")+rs.getInt("successful_subscriptions__2_afn_eb")+rs.getInt("successful_subscriptions__2_afn_ec")+rs.getInt("successful_subscriptions__2_afn_epu")+rs.getInt("successful_subscriptions__2_afn_es")+rs.getInt("successful_subscriptions__2_afn_eho")+rs.getInt("successful_subscriptions__2_afn_kk")+rs.getInt("successful_subscriptions__2_afn_nb")+rs.getInt("successful_subscriptions__2_afn_nh")+rs.getInt("successful_subscriptions__2_afn_nw")+rs.getInt("successful_subscriptions__2_afn_nwe")+rs.getInt("successful_subscriptions__2_afn_ns")+rs.getInt("successful_subscriptions__2_afn_nsh")+rs.getInt("successful_subscriptions__2_afn_fc")+rs.getInt("successful_subscriptions__2_afn_ff")+rs.getInt("successful_subscriptions__2_afn_fg")+rs.getInt("successful_subscriptions__2_afn_fgr");
				 total_resub_req_rec_15=rs.getInt("subscription_retry__15_afn_eq")+rs.getInt("subscription_retry__15_afn_ej")+rs.getInt("subscription_retry__15_afn_eh")+rs.getInt("subscription_retry__15_afn_ep")+rs.getInt("subscription_retry__15_afn_eb")+rs.getInt("subscription_retry__15_afn_ec")+rs.getInt("subscription_retry__15_afn_epu")+rs.getInt("subscription_retry__15_afn_es")+rs.getInt("subscription_retry__15_afn_eho")+rs.getInt("subscription_retry__15_afn_kk")+rs.getInt("subscription_retry__15_afn_nb")+rs.getInt("subscription_retry__15_afn_nh")+rs.getInt("subscription_retry__15_afn_nw")+rs.getInt("subscription_retry__15_afn_nwe")+rs.getInt("subscription_retry__15_afn_ns")+rs.getInt("subscription_retry__15_afn_nsh")+rs.getInt("subscription_retry__15_afn_fc")+rs.getInt("subscription_retry__15_afn_ff")+rs.getInt("subscription_retry__15_afn_fg")+rs.getInt("subscription_retry__15_afn_fgr");
				 total_resub_req_rec_5=rs.getInt("subscription_retry__5_afn_eq")+rs.getInt("subscription_retry__5_afn_ej")+rs.getInt("subscription_retry__5_afn_eh")+rs.getInt("subscription_retry__5_afn_ep")+rs.getInt("subscription_retry__5_afn_eb")+rs.getInt("subscription_retry__5_afn_ec")+rs.getInt("subscription_retry__5_afn_epu")+rs.getInt("subscription_retry__5_afn_es")+rs.getInt("subscription_retry__5_afn_eho")+rs.getInt("subscription_retry__5_afn_kk")+rs.getInt("subscription_retry__5_afn_nb")+rs.getInt("subscription_retry__5_afn_nh")+rs.getInt("subscription_retry__5_afn_nw")+rs.getInt("subscription_retry__5_afn_nwe")+rs.getInt("subscription_retry__5_afn_ns")+rs.getInt("subscription_retry__5_afn_nsh")+rs.getInt("subscription_retry__5_afn_fc")+rs.getInt("subscription_retry__5_afn_ff")+rs.getInt("subscription_retry__5_afn_fg")+rs.getInt("subscription_retry__5_afn_fgr");
				 total_resub_req_rec_2=rs.getInt("subscription_retry__2_afn_eq")+rs.getInt("subscription_retry__2_afn_ej")+rs.getInt("subscription_retry__2_afn_eh")+rs.getInt("subscription_retry__2_afn_ep")+rs.getInt("subscription_retry__2_afn_eb")+rs.getInt("subscription_retry__2_afn_ec")+rs.getInt("subscription_retry__2_afn_epu")+rs.getInt("subscription_retry__2_afn_es")+rs.getInt("subscription_retry__2_afn_eho")+rs.getInt("subscription_retry__2_afn_kk")+rs.getInt("subscription_retry__2_afn_nb")+rs.getInt("subscription_retry__2_afn_nh")+rs.getInt("subscription_retry__2_afn_nw")+rs.getInt("subscription_retry__2_afn_nwe")+rs.getInt("subscription_retry__2_afn_ns")+rs.getInt("subscription_retry__2_afn_nsh")+rs.getInt("subscription_retry__2_afn_fc")+rs.getInt("subscription_retry__2_afn_ff")+rs.getInt("subscription_retry__2_afn_fg")+rs.getInt("subscription_retry__2_afn_fgr");
				 total_resub_suc_15=rs.getInt("retry_successfull__15_afn_eq")+rs.getInt("retry_successfull__15_afn_ej")+rs.getInt("retry_successfull__15_afn_eh")+rs.getInt("retry_successfull__15_afn_ep")+rs.getInt("retry_successfull__15_afn_eb")+rs.getInt("retry_successfull__15_afn_ec")+rs.getInt("retry_successfull__15_afn_epu")+rs.getInt("retry_successfull__15_afn_es")+rs.getInt("retry_successfull__15_afn_eho")+rs.getInt("retry_successfull__15_afn_kk")+rs.getInt("retry_successfull__15_afn_nb")+rs.getInt("retry_successfull__15_afn_nh")+rs.getInt("retry_successfull__15_afn_nw")+rs.getInt("retry_successfull__15_afn_nwe")+rs.getInt("retry_successfull__15_afn_ns")+rs.getInt("retry_successfull__15_afn_nsh")+rs.getInt("retry_successfull__15_afn_fc")+rs.getInt("retry_successfull__15_afn_ff")+rs.getInt("retry_successfull__15_afn_fg")+rs.getInt("retry_successfull__15_afn_fgr");
				 total_resub_suc_5=rs.getInt("retry_successfull__5_afn_eq")+rs.getInt("retry_successfull__5_afn_ej")+rs.getInt("retry_successfull__5_afn_eh")+rs.getInt("retry_successfull__5_afn_ep")+rs.getInt("retry_successfull__5_afn_eb")+rs.getInt("retry_successfull__5_afn_ec")+rs.getInt("retry_successfull__5_afn_epu")+rs.getInt("retry_successfull__5_afn_es")+rs.getInt("retry_successfull__5_afn_eho")+rs.getInt("retry_successfull__5_afn_kk")+rs.getInt("retry_successfull__5_afn_nb")+rs.getInt("retry_successfull__5_afn_nh")+rs.getInt("retry_successfull__5_afn_nw")+rs.getInt("retry_successfull__5_afn_nwe")+rs.getInt("retry_successfull__5_afn_ns")+rs.getInt("retry_successfull__5_afn_nsh")+rs.getInt("retry_successfull__5_afn_fc")+rs.getInt("retry_successfull__5_afn_ff")+rs.getInt("retry_successfull__5_afn_fg")+rs.getInt("retry_successfull__5_afn_fgr");
				 total_resub_suc_2=rs.getInt("retry_successfull__2_afn_eq")+rs.getInt("retry_successfull__2_afn_ej")+rs.getInt("retry_successfull__2_afn_eh")+rs.getInt("retry_successfull__2_afn_ep")+rs.getInt("retry_successfull__2_afn_eb")+rs.getInt("retry_successfull__2_afn_ec")+rs.getInt("retry_successfull__2_afn_epu")+rs.getInt("retry_successfull__2_afn_es")+rs.getInt("retry_successfull__2_afn_eho")+rs.getInt("retry_successfull__2_afn_kk")+rs.getInt("retry_successfull__2_afn_nb")+rs.getInt("retry_successfull__2_afn_nh")+rs.getInt("retry_successfull__2_afn_nw")+rs.getInt("retry_successfull__2_afn_nwe")+rs.getInt("retry_successfull__2_afn_ns")+rs.getInt("retry_successfull__2_afn_nsh")+rs.getInt("retry_successfull__2_afn_fc")+rs.getInt("retry_successfull__2_afn_ff")+rs.getInt("retry_successfull__2_afn_fg")+rs.getInt("retry_successfull__2_afn_fgr");
				 total_sub_revenue=rs.getInt("total_subscription_revenue_eq")+rs.getInt("total_subscription_revenue_ej")+rs.getInt("total_subscription_revenue_eh")+rs.getInt("total_subscription_revenue_ep")+rs.getInt("total_subscription_revenue_eb")+rs.getInt("total_subscription_revenue_ec")+rs.getInt("total_subscription_revenue_epu")+rs.getInt("total_subscription_revenue_es")+rs.getInt("total_subscription_revenue_eho")+rs.getInt("total_subscription_revenue_kk")+rs.getInt("total_subscription_revenue_nb")+rs.getInt("total_subscription_revenue_nh")+rs.getInt("total_subscription_revenue_nw")+rs.getInt("total_subscription_revenue_nwe")+rs.getInt("total_subscription_revenue_ns")+rs.getInt("total_subscription_revenue_nsh")+rs.getInt("total_subscription_revenue_fc")+rs.getInt("total_subscription_revenue_ff")+rs.getInt("total_subscription_revenue_fg")+rs.getInt("total_subscription_revenue_fgr");
				 total_resub_revenue=rs.getInt("total_resubscription_revenue_eq")+rs.getInt("total_resubscription_revenue_ej")+rs.getInt("total_resubscription_revenue_eh")+rs.getInt("total_resubscription_revenue_ep")+rs.getInt("total_resubscription_revenue_eb")+rs.getInt("total_resubscription_revenue_ec")+rs.getInt("total_resubscription_revenue_epu")+rs.getInt("total_resubscription_revenue_es")+rs.getInt("total_resubscription_revenue_eho")+rs.getInt("total_resubscription_revenue_kk")+rs.getInt("total_resubscription_revenue_nb")+rs.getInt("total_resubscription_revenue_nh")+rs.getInt("total_resubscription_revenue_nw")+rs.getInt("total_resubscription_revenue_nwe")+rs.getInt("total_resubscription_revenue_ns")+rs.getInt("total_resubscription_revenue_nsh")+rs.getInt("total_resubscription_revenue_fc")+rs.getInt("total_resubscription_revenue_ff")+rs.getInt("total_resubscription_revenue_fg")+rs.getInt("total_resubscription_revenue_fgr");
				 s[i].put("subscription_requests_received__15_afn_eq", rs.getString("subscription_requests_received__15_afn_eq"));
				 s[i].put("subscription_requests_received__5_afn_eq", rs.getString("subscription_requests_received__5_afn_eq"));
				 s[i].put("subscription_requests_received__2_afn_eq", rs.getString("subscription_requests_received__2_afn_eq"));
				 s[i].put("successful_subscriptions__15_afn_eq", rs.getString("successful_subscriptions__15_afn_eq"));
				 s[i].put("successful_subscriptions__5_afn_eq", rs.getString("successful_subscriptions__5_afn_eq"));
				 s[i].put("successful_subscriptions__2_afn_eq", rs.getString("successful_subscriptions__2_afn_eq"));
				 s[i].put("subscription_retry__15_afn_eq", rs.getString("subscription_retry__15_afn_eq"));
				 s[i].put("subscription_retry__5_afn_eq", rs.getString("subscription_retry__5_afn_eq"));
				 s[i].put("subscription_retry__2_afn_eq", rs.getString("subscription_retry__2_afn_eq"));
				 s[i].put("retry_successfull__15_afn_eq", rs.getString("retry_successfull__15_afn_eq"));
				 s[i].put("retry_successfull__5_afn_eq", rs.getString("retry_successfull__5_afn_eq"));
				 s[i].put("retry_successfull__2_afn_eq", rs.getString("retry_successfull__2_afn_eq"));
				 s[i].put("total_subscription_revenue_eq", rs.getString("total_subscription_revenue_eq"));
				 s[i].put("total_resubscription_revenue_eq", rs.getString("total_resubscription_revenue_eq"));
				 s[i].put("subscription_requests_received__15_afn_ej", rs.getString("subscription_requests_received__15_afn_ej"));
				 s[i].put("subscription_requests_received__5_afn_ej", rs.getString("subscription_requests_received__5_afn_ej"));
				 s[i].put("subscription_requests_received__2_afn_ej", rs.getString("subscription_requests_received__2_afn_ej"));
				 s[i].put("successful_subscriptions__15_afn_ej", rs.getString("successful_subscriptions__15_afn_ej"));
				 s[i].put("successful_subscriptions__5_afn_ej", rs.getString("successful_subscriptions__5_afn_ej"));
				 s[i].put("successful_subscriptions__2_afn_ej", rs.getString("successful_subscriptions__2_afn_ej"));
				 s[i].put("subscription_retry__15_afn_ej", rs.getString("subscription_retry__15_afn_ej"));
				 s[i].put("subscription_retry__5_afn_ej", rs.getString("subscription_retry__5_afn_ej"));
				 s[i].put("subscription_retry__2_afn_ej", rs.getString("subscription_retry__2_afn_ej"));
				 s[i].put("retry_successfull__15_afn_ej", rs.getString("retry_successfull__15_afn_ej"));
				 s[i].put("retry_successfull__5_afn_ej", rs.getString("retry_successfull__5_afn_ej"));
				 s[i].put("retry_successfull__2_afn_ej", rs.getString("retry_successfull__2_afn_ej"));
				 s[i].put("total_subscription_revenue_ej", rs.getString("total_subscription_revenue_ej"));
				 s[i].put("total_resubscription_revenue_ej", rs.getString("total_resubscription_revenue_ej"));
				 s[i].put("subscription_requests_received__15_afn_eh", rs.getString("subscription_requests_received__15_afn_eh"));
				 s[i].put("subscription_requests_received__5_afn_eh", rs.getString("subscription_requests_received__5_afn_eh"));
				 s[i].put("subscription_requests_received__2_afn_eh", rs.getString("subscription_requests_received__2_afn_eh"));
				 s[i].put("successful_subscriptions__15_afn_eh", rs.getString("successful_subscriptions__15_afn_eh"));
				 s[i].put("successful_subscriptions__5_afn_eh", rs.getString("successful_subscriptions__5_afn_eh"));
				 s[i].put("successful_subscriptions__2_afn_eh", rs.getString("successful_subscriptions__2_afn_eh"));
				 s[i].put("subscription_retry__15_afn_eh", rs.getString("subscription_retry__15_afn_eh"));
				 s[i].put("subscription_retry__5_afn_eh", rs.getString("subscription_retry__5_afn_eh"));
				 s[i].put("subscription_retry__2_afn_eh", rs.getString("subscription_retry__2_afn_eh"));
				 s[i].put("retry_successfull__15_afn_eh", rs.getString("retry_successfull__15_afn_eh"));
				 s[i].put("retry_successfull__5_afn_eh", rs.getString("retry_successfull__5_afn_eh"));
				 s[i].put("retry_successfull__2_afn_eh", rs.getString("retry_successfull__2_afn_eh"));
				 s[i].put("total_subscription_revenue_eh", rs.getString("total_subscription_revenue_eh"));
				 s[i].put("total_resubscription_revenue_eh", rs.getString("total_resubscription_revenue_eh"));
				 s[i].put("subscription_requests_received__15_afn_ep", rs.getString("subscription_requests_received__15_afn_ep"));
				 s[i].put("subscription_requests_received__5_afn_ep", rs.getString("subscription_requests_received__5_afn_ep"));
				 s[i].put("subscription_requests_received__2_afn_ep", rs.getString("subscription_requests_received__2_afn_ep"));
				 s[i].put("successful_subscriptions__15_afn_ep", rs.getString("successful_subscriptions__15_afn_ep"));
				 s[i].put("successful_subscriptions__5_afn_ep", rs.getString("successful_subscriptions__5_afn_ep"));
				 s[i].put("successful_subscriptions__2_afn_ep", rs.getString("successful_subscriptions__2_afn_ep"));
				 s[i].put("subscription_retry__15_afn_ep", rs.getString("subscription_retry__15_afn_ep"));
				 s[i].put("subscription_retry__5_afn_ep", rs.getString("subscription_retry__5_afn_ep"));
				 s[i].put("subscription_retry__2_afn_ep", rs.getString("subscription_retry__2_afn_ep"));
				 s[i].put("retry_successfull__15_afn_ep", rs.getString("retry_successfull__15_afn_ep"));
				 s[i].put("retry_successfull__5_afn_ep", rs.getString("retry_successfull__5_afn_ep"));
				 s[i].put("retry_successfull__2_afn_ep", rs.getString("retry_successfull__2_afn_ep"));
				 s[i].put("total_subscription_revenue_ep", rs.getString("total_subscription_revenue_ep"));
				 s[i].put("total_resubscription_revenue_ep", rs.getString("total_resubscription_revenue_ep"));
				 s[i].put("subscription_requests_received__15_afn_eb", rs.getString("subscription_requests_received__15_afn_eb"));
				 s[i].put("subscription_requests_received__5_afn_eb", rs.getString("subscription_requests_received__5_afn_eb"));
				 s[i].put("subscription_requests_received__2_afn_eb", rs.getString("subscription_requests_received__2_afn_eb"));
				 s[i].put("successful_subscriptions__15_afn_eb", rs.getString("successful_subscriptions__15_afn_eb"));
				 s[i].put("successful_subscriptions__5_afn_eb", rs.getString("successful_subscriptions__5_afn_eb"));
				 s[i].put("successful_subscriptions__2_afn_eb", rs.getString("successful_subscriptions__2_afn_eb"));
				 s[i].put("subscription_retry__15_afn_eb", rs.getString("subscription_retry__15_afn_eb"));
				 s[i].put("subscription_retry__5_afn_eb", rs.getString("subscription_retry__5_afn_eb"));
				 s[i].put("subscription_retry__2_afn_eb", rs.getString("subscription_retry__2_afn_eb"));
				 s[i].put("retry_successfull__15_afn_eb", rs.getString("retry_successfull__15_afn_eb"));
				 s[i].put("retry_successfull__5_afn_eb", rs.getString("retry_successfull__5_afn_eb"));
				 s[i].put("retry_successfull__2_afn_eb", rs.getString("retry_successfull__2_afn_eb"));
				 s[i].put("total_subscription_revenue_eb", rs.getString("total_subscription_revenue_eb"));
				 s[i].put("total_resubscription_revenue_eb", rs.getString("total_resubscription_revenue_eb"));
				 s[i].put("subscription_requests_received__15_afn_ec", rs.getString("subscription_requests_received__15_afn_ec"));
				 s[i].put("subscription_requests_received__5_afn_ec", rs.getString("subscription_requests_received__5_afn_ec"));
				 s[i].put("subscription_requests_received__2_afn_ec", rs.getString("subscription_requests_received__2_afn_ec"));
				 s[i].put("successful_subscriptions__15_afn_ec", rs.getString("successful_subscriptions__15_afn_ec"));
				 s[i].put("successful_subscriptions__5_afn_ec", rs.getString("successful_subscriptions__5_afn_ec"));
				 s[i].put("successful_subscriptions__2_afn_ec", rs.getString("successful_subscriptions__2_afn_ec"));
				 s[i].put("subscription_retry__15_afn_ec", rs.getString("subscription_retry__15_afn_ec"));
				 s[i].put("subscription_retry__5_afn_ec", rs.getString("subscription_retry__5_afn_ec"));
				 s[i].put("subscription_retry__2_afn_ec", rs.getString("subscription_retry__2_afn_ec"));
				 s[i].put("retry_successfull__15_afn_ec", rs.getString("retry_successfull__15_afn_ec"));
				 s[i].put("retry_successfull__5_afn_ec", rs.getString("retry_successfull__5_afn_ec"));
				 s[i].put("retry_successfull__2_afn_ec", rs.getString("retry_successfull__2_afn_ec"));
				 s[i].put("total_subscription_revenue_ec", rs.getString("total_subscription_revenue_ec"));
				 s[i].put("total_resubscription_revenue_ec", rs.getString("total_resubscription_revenue_ec"));
				 s[i].put("subscription_requests_received__15_afn_epu", rs.getString("subscription_requests_received__15_afn_epu"));
				 s[i].put("subscription_requests_received__5_afn_epu", rs.getString("subscription_requests_received__5_afn_epu"));
				 s[i].put("subscription_requests_received__2_afn_epu", rs.getString("subscription_requests_received__2_afn_epu"));
				 s[i].put("successful_subscriptions__15_afn_epu", rs.getString("successful_subscriptions__15_afn_epu"));
				 s[i].put("successful_subscriptions__5_afn_epu", rs.getString("successful_subscriptions__5_afn_epu"));
				 s[i].put("successful_subscriptions__2_afn_epu", rs.getString("successful_subscriptions__2_afn_epu"));
				 s[i].put("subscription_retry__15_afn_epu", rs.getString("subscription_retry__15_afn_epu"));
				 s[i].put("subscription_retry__5_afn_epu", rs.getString("subscription_retry__5_afn_epu"));
				 s[i].put("subscription_retry__2_afn_epu", rs.getString("subscription_retry__2_afn_epu"));
				 s[i].put("retry_successfull__15_afn_epu", rs.getString("retry_successfull__15_afn_epu"));
				 s[i].put("retry_successfull__5_afn_epu", rs.getString("retry_successfull__5_afn_epu"));
				 s[i].put("retry_successfull__2_afn_epu", rs.getString("retry_successfull__2_afn_epu"));
				 s[i].put("total_subscription_revenue_epu", rs.getString("total_subscription_revenue_epu"));
				 s[i].put("total_resubscription_revenue_epu", rs.getString("total_resubscription_revenue_epu"));
				 s[i].put("subscription_requests_received__15_afn_es", rs.getString("subscription_requests_received__15_afn_es"));
				 s[i].put("subscription_requests_received__5_afn_es", rs.getString("subscription_requests_received__5_afn_es"));
				 s[i].put("subscription_requests_received__2_afn_es", rs.getString("subscription_requests_received__2_afn_es"));
				 s[i].put("successful_subscriptions__15_afn_es", rs.getString("successful_subscriptions__15_afn_es"));
				 s[i].put("successful_subscriptions__5_afn_es", rs.getString("successful_subscriptions__5_afn_es"));
				 s[i].put("successful_subscriptions__2_afn_es", rs.getString("successful_subscriptions__2_afn_es"));
				 s[i].put("subscription_retry__15_afn_es", rs.getString("subscription_retry__15_afn_es"));
				 s[i].put("subscription_retry__5_afn_es", rs.getString("subscription_retry__5_afn_es"));
				 s[i].put("subscription_retry__2_afn_es", rs.getString("subscription_retry__2_afn_es"));
				 s[i].put("retry_successfull__15_afn_es", rs.getString("retry_successfull__15_afn_es"));
				 s[i].put("retry_successfull__5_afn_es", rs.getString("retry_successfull__5_afn_es"));
				 s[i].put("retry_successfull__2_afn_es", rs.getString("retry_successfull__2_afn_es"));
				 s[i].put("total_subscription_revenue_es", rs.getString("total_subscription_revenue_es"));
				 s[i].put("total_resubscription_revenue_es", rs.getString("total_resubscription_revenue_es"));
				 s[i].put("subscription_requests_received__15_afn_eho", rs.getString("subscription_requests_received__15_afn_eho"));
				 s[i].put("subscription_requests_received__5_afn_eho", rs.getString("subscription_requests_received__5_afn_eho"));
				 s[i].put("subscription_requests_received__2_afn_eho", rs.getString("subscription_requests_received__2_afn_eho"));
				 s[i].put("successful_subscriptions__15_afn_eho", rs.getString("successful_subscriptions__15_afn_eho"));
				 s[i].put("successful_subscriptions__5_afn_eho", rs.getString("successful_subscriptions__5_afn_eho"));
				 s[i].put("successful_subscriptions__2_afn_eho", rs.getString("successful_subscriptions__2_afn_eho"));
				 s[i].put("subscription_retry__15_afn_eho", rs.getString("subscription_retry__15_afn_eho"));
				 s[i].put("subscription_retry__5_afn_eho", rs.getString("subscription_retry__5_afn_eho"));
				 s[i].put("subscription_retry__2_afn_eho", rs.getString("subscription_retry__2_afn_eho"));
				 s[i].put("retry_successfull__15_afn_eho", rs.getString("retry_successfull__15_afn_eho"));
				 s[i].put("retry_successfull__5_afn_eho", rs.getString("retry_successfull__5_afn_eho"));
				 s[i].put("retry_successfull__2_afn_eho", rs.getString("retry_successfull__2_afn_eho"));
				 s[i].put("total_subscription_revenue_eho", rs.getString("total_subscription_revenue_eho"));
				 s[i].put("total_resubscription_revenue_eho", rs.getString("total_resubscription_revenue_eho"));
				 s[i].put("subscription_requests_received__15_afn_kk", rs.getString("subscription_requests_received__15_afn_kk"));
				 s[i].put("subscription_requests_received__5_afn_kk", rs.getString("subscription_requests_received__5_afn_kk"));
				 s[i].put("subscription_requests_received__2_afn_kk", rs.getString("subscription_requests_received__2_afn_kk"));
				 s[i].put("successful_subscriptions__15_afn_kk", rs.getString("successful_subscriptions__15_afn_kk"));
				 s[i].put("successful_subscriptions__5_afn_kk", rs.getString("successful_subscriptions__5_afn_kk"));
				 s[i].put("successful_subscriptions__2_afn_kk", rs.getString("successful_subscriptions__2_afn_kk"));
				 s[i].put("subscription_retry__15_afn_kk", rs.getString("subscription_retry__15_afn_kk"));
				 s[i].put("subscription_retry__5_afn_kk", rs.getString("subscription_retry__5_afn_kk"));
				 s[i].put("subscription_retry__2_afn_kk", rs.getString("subscription_retry__2_afn_kk"));
				 s[i].put("retry_successfull__15_afn_kk", rs.getString("retry_successfull__15_afn_kk"));
				 s[i].put("retry_successfull__5_afn_kk", rs.getString("retry_successfull__5_afn_kk"));
				 s[i].put("retry_successfull__2_afn_kk", rs.getString("retry_successfull__2_afn_kk"));
				 s[i].put("total_subscription_revenue_kk", rs.getString("total_subscription_revenue_kk"));
				 s[i].put("total_resubscription_revenue_kk", rs.getString("total_resubscription_revenue_kk"));
				 s[i].put("subscription_requests_received__15_afn_nb", rs.getString("subscription_requests_received__15_afn_nb"));
				 s[i].put("subscription_requests_received__5_afn_nb", rs.getString("subscription_requests_received__5_afn_nb"));
				 s[i].put("subscription_requests_received__2_afn_nb", rs.getString("subscription_requests_received__2_afn_nb"));
				 s[i].put("successful_subscriptions__15_afn_nb", rs.getString("successful_subscriptions__15_afn_nb"));
				 s[i].put("successful_subscriptions__5_afn_nb", rs.getString("successful_subscriptions__5_afn_nb"));
				 s[i].put("successful_subscriptions__2_afn_nb", rs.getString("successful_subscriptions__2_afn_nb"));
				 s[i].put("subscription_retry__15_afn_nb", rs.getString("subscription_retry__15_afn_nb"));
				 s[i].put("subscription_retry__5_afn_nb", rs.getString("subscription_retry__5_afn_nb"));
				 s[i].put("subscription_retry__2_afn_nb", rs.getString("subscription_retry__2_afn_nb"));
				 s[i].put("retry_successfull__15_afn_nb", rs.getString("retry_successfull__15_afn_nb"));
				 s[i].put("retry_successfull__5_afn_nb", rs.getString("retry_successfull__5_afn_nb"));
				 s[i].put("retry_successfull__2_afn_nb", rs.getString("retry_successfull__2_afn_nb"));
				 s[i].put("total_subscription_revenue_nb", rs.getString("total_subscription_revenue_nb"));
				 s[i].put("total_resubscription_revenue_nb", rs.getString("total_resubscription_revenue_nb"));
				 s[i].put("subscription_requests_received__15_afn_nh", rs.getString("subscription_requests_received__15_afn_nh"));
				 s[i].put("subscription_requests_received__5_afn_nh", rs.getString("subscription_requests_received__5_afn_nh"));
				 s[i].put("subscription_requests_received__2_afn_nh", rs.getString("subscription_requests_received__2_afn_nh"));
				 s[i].put("successful_subscriptions__15_afn_nh", rs.getString("successful_subscriptions__15_afn_nh"));
				 s[i].put("successful_subscriptions__5_afn_nh", rs.getString("successful_subscriptions__5_afn_nh"));
				 s[i].put("successful_subscriptions__2_afn_nh", rs.getString("successful_subscriptions__2_afn_nh"));
				 s[i].put("subscription_retry__15_afn_nh", rs.getString("subscription_retry__15_afn_nh"));
				 s[i].put("subscription_retry__5_afn_nh", rs.getString("subscription_retry__5_afn_nh"));
				 s[i].put("subscription_retry__2_afn_nh", rs.getString("subscription_retry__2_afn_nh"));
				 s[i].put("retry_successfull__15_afn_nh", rs.getString("retry_successfull__15_afn_nh"));
				 s[i].put("retry_successfull__5_afn_nh", rs.getString("retry_successfull__5_afn_nh"));
				 s[i].put("retry_successfull__2_afn_nh", rs.getString("retry_successfull__2_afn_nh"));
				 s[i].put("total_subscription_revenue_nh", rs.getString("total_subscription_revenue_nh"));
				 s[i].put("total_resubscription_revenue_nh", rs.getString("total_resubscription_revenue_nh"));
				 s[i].put("subscription_requests_received__15_afn_nw", rs.getString("subscription_requests_received__15_afn_nw"));
				 s[i].put("subscription_requests_received__5_afn_nw", rs.getString("subscription_requests_received__5_afn_nw"));
				 s[i].put("subscription_requests_received__2_afn_nw", rs.getString("subscription_requests_received__2_afn_nw"));
				 s[i].put("successful_subscriptions__15_afn_nw", rs.getString("successful_subscriptions__15_afn_nw"));
				 s[i].put("successful_subscriptions__5_afn_nw", rs.getString("successful_subscriptions__5_afn_nw"));
				 s[i].put("successful_subscriptions__2_afn_nw", rs.getString("successful_subscriptions__2_afn_nw"));
				 s[i].put("subscription_retry__15_afn_nw", rs.getString("subscription_retry__15_afn_nw"));
				 s[i].put("subscription_retry__5_afn_nw", rs.getString("subscription_retry__5_afn_nw"));
				 s[i].put("subscription_retry__2_afn_nw", rs.getString("subscription_retry__2_afn_nw"));
				 s[i].put("retry_successfull__15_afn_nw", rs.getString("retry_successfull__15_afn_nw"));
				 s[i].put("retry_successfull__5_afn_nw", rs.getString("retry_successfull__5_afn_nw"));
				 s[i].put("retry_successfull__2_afn_nw", rs.getString("retry_successfull__2_afn_nw"));
				 s[i].put("total_subscription_revenue_nw", rs.getString("total_subscription_revenue_nw"));
				 s[i].put("total_resubscription_revenue_nw", rs.getString("total_resubscription_revenue_nw"));
				 s[i].put("subscription_requests_received__15_afn_nwe", rs.getString("subscription_requests_received__15_afn_nwe"));
				 s[i].put("subscription_requests_received__5_afn_nwe", rs.getString("subscription_requests_received__5_afn_nwe"));
				 s[i].put("subscription_requests_received__2_afn_nwe", rs.getString("subscription_requests_received__2_afn_nwe"));
				 s[i].put("successful_subscriptions__15_afn_nwe", rs.getString("successful_subscriptions__15_afn_nwe"));
				 s[i].put("successful_subscriptions__5_afn_nwe", rs.getString("successful_subscriptions__5_afn_nwe"));
				 s[i].put("successful_subscriptions__2_afn_nwe", rs.getString("successful_subscriptions__2_afn_nwe"));
				 s[i].put("subscription_retry__15_afn_nwe", rs.getString("subscription_retry__15_afn_nwe"));
				 s[i].put("subscription_retry__5_afn_nwe", rs.getString("subscription_retry__5_afn_nwe"));
				 s[i].put("subscription_retry__2_afn_nwe", rs.getString("subscription_retry__2_afn_nwe"));
				 s[i].put("retry_successfull__15_afn_nwe", rs.getString("retry_successfull__15_afn_nwe"));
				 s[i].put("retry_successfull__5_afn_nwe", rs.getString("retry_successfull__5_afn_nwe"));
				 s[i].put("retry_successfull__2_afn_nwe", rs.getString("retry_successfull__2_afn_nwe"));
				 s[i].put("total_subscription_revenue_nwe", rs.getString("total_subscription_revenue_nwe"));
				 s[i].put("total_resubscription_revenue_nwe", rs.getString("total_resubscription_revenue_nwe"));
				 s[i].put("subscription_requests_received__15_afn_ns", rs.getString("subscription_requests_received__15_afn_ns"));
				 s[i].put("subscription_requests_received__5_afn_ns", rs.getString("subscription_requests_received__5_afn_ns"));
				 s[i].put("subscription_requests_received__2_afn_ns", rs.getString("subscription_requests_received__2_afn_ns"));
				 s[i].put("successful_subscriptions__15_afn_ns", rs.getString("successful_subscriptions__15_afn_ns"));
				 s[i].put("successful_subscriptions__5_afn_ns", rs.getString("successful_subscriptions__5_afn_ns"));
				 s[i].put("successful_subscriptions__2_afn_ns", rs.getString("successful_subscriptions__2_afn_ns"));
				 s[i].put("subscription_retry__15_afn_ns", rs.getString("subscription_retry__15_afn_ns"));
				 s[i].put("subscription_retry__5_afn_ns", rs.getString("subscription_retry__5_afn_ns"));
				 s[i].put("subscription_retry__2_afn_ns", rs.getString("subscription_retry__2_afn_ns"));
				 s[i].put("retry_successfull__15_afn_ns", rs.getString("retry_successfull__15_afn_ns"));
				 s[i].put("retry_successfull__5_afn_ns", rs.getString("retry_successfull__5_afn_ns"));
				 s[i].put("retry_successfull__2_afn_ns", rs.getString("retry_successfull__2_afn_ns"));
				 s[i].put("total_subscription_revenue_ns", rs.getString("total_subscription_revenue_ns"));
				 s[i].put("total_resubscription_revenue_ns", rs.getString("total_resubscription_revenue_ns"));
				 s[i].put("subscription_requests_received__15_afn_nsh", rs.getString("subscription_requests_received__15_afn_nsh"));
				 s[i].put("subscription_requests_received__5_afn_nsh", rs.getString("subscription_requests_received__5_afn_nsh"));
				 s[i].put("subscription_requests_received__2_afn_nsh", rs.getString("subscription_requests_received__2_afn_nsh"));
				 s[i].put("successful_subscriptions__15_afn_nsh", rs.getString("successful_subscriptions__15_afn_nsh"));
				 s[i].put("successful_subscriptions__5_afn_nsh", rs.getString("successful_subscriptions__5_afn_nsh"));
				 s[i].put("successful_subscriptions__2_afn_nsh", rs.getString("successful_subscriptions__2_afn_nsh"));
				 s[i].put("subscription_retry__15_afn_nsh", rs.getString("subscription_retry__15_afn_nsh"));
				 s[i].put("subscription_retry__5_afn_nsh", rs.getString("subscription_retry__5_afn_nsh"));
				 s[i].put("subscription_retry__2_afn_nsh", rs.getString("subscription_retry__2_afn_nsh"));
				 s[i].put("retry_successfull__15_afn_nsh", rs.getString("retry_successfull__15_afn_nsh"));
				 s[i].put("retry_successfull__5_afn_nsh", rs.getString("retry_successfull__5_afn_nsh"));
				 s[i].put("retry_successfull__2_afn_nsh", rs.getString("retry_successfull__2_afn_nsh"));
				 s[i].put("total_subscription_revenue_nsh", rs.getString("total_subscription_revenue_nsh"));
				 s[i].put("total_resubscription_revenue_nsh", rs.getString("total_resubscription_revenue_nsh"));
				 s[i].put("subscription_requests_received__15_afn_fc", rs.getString("subscription_requests_received__15_afn_fc"));
				 s[i].put("subscription_requests_received__5_afn_fc", rs.getString("subscription_requests_received__5_afn_fc"));
				 s[i].put("subscription_requests_received__2_afn_fc", rs.getString("subscription_requests_received__2_afn_fc"));
				 s[i].put("successful_subscriptions__15_afn_fc", rs.getString("successful_subscriptions__15_afn_fc"));
				 s[i].put("successful_subscriptions__5_afn_fc", rs.getString("successful_subscriptions__5_afn_fc"));
				 s[i].put("successful_subscriptions__2_afn_fc", rs.getString("successful_subscriptions__2_afn_fc"));
				 s[i].put("subscription_retry__15_afn_fc", rs.getString("subscription_retry__15_afn_fc"));
				 s[i].put("subscription_retry__5_afn_fc", rs.getString("subscription_retry__5_afn_fc"));
				 s[i].put("subscription_retry__2_afn_fc", rs.getString("subscription_retry__2_afn_fc"));
				 s[i].put("retry_successfull__15_afn_fc", rs.getString("retry_successfull__15_afn_fc"));
				 s[i].put("retry_successfull__5_afn_fc", rs.getString("retry_successfull__5_afn_fc"));
				 s[i].put("retry_successfull__2_afn_fc", rs.getString("retry_successfull__2_afn_fc"));
				 s[i].put("total_subscription_revenue_fc", rs.getString("total_subscription_revenue_fc"));
				 s[i].put("total_resubscription_revenue_fc", rs.getString("total_resubscription_revenue_fc"));
				 s[i].put("subscription_requests_received__15_afn_ff", rs.getString("subscription_requests_received__15_afn_ff"));
				 s[i].put("subscription_requests_received__5_afn_ff", rs.getString("subscription_requests_received__5_afn_ff"));
				 s[i].put("subscription_requests_received__2_afn_ff", rs.getString("subscription_requests_received__2_afn_ff"));
				 s[i].put("successful_subscriptions__15_afn_ff", rs.getString("successful_subscriptions__15_afn_ff"));
				 s[i].put("successful_subscriptions__5_afn_ff", rs.getString("successful_subscriptions__5_afn_ff"));
				 s[i].put("successful_subscriptions__2_afn_ff", rs.getString("successful_subscriptions__2_afn_ff"));
				 s[i].put("subscription_retry__15_afn_ff", rs.getString("subscription_retry__15_afn_ff"));
				 s[i].put("subscription_retry__5_afn_ff", rs.getString("subscription_retry__5_afn_ff"));
				 s[i].put("subscription_retry__2_afn_ff", rs.getString("subscription_retry__2_afn_ff"));
				 s[i].put("retry_successfull__15_afn_ff", rs.getString("retry_successfull__15_afn_ff"));
				 s[i].put("retry_successfull__5_afn_ff", rs.getString("retry_successfull__5_afn_ff"));
				 s[i].put("retry_successfull__2_afn_ff", rs.getString("retry_successfull__2_afn_ff"));
				 s[i].put("total_subscription_revenue_ff", rs.getString("total_subscription_revenue_ff"));
				 s[i].put("total_resubscription_revenue_ff", rs.getString("total_resubscription_revenue_ff"));
				 s[i].put("subscription_requests_received__15_afn_fg", rs.getString("subscription_requests_received__15_afn_fg"));
				 s[i].put("subscription_requests_received__5_afn_fg", rs.getString("subscription_requests_received__5_afn_fg"));
				 s[i].put("subscription_requests_received__2_afn_fg", rs.getString("subscription_requests_received__2_afn_fg"));
				 s[i].put("successful_subscriptions__15_afn_fg", rs.getString("successful_subscriptions__15_afn_fg"));
				 s[i].put("successful_subscriptions__5_afn_fg", rs.getString("successful_subscriptions__5_afn_fg"));
				 s[i].put("successful_subscriptions__2_afn_fg", rs.getString("successful_subscriptions__2_afn_fg"));
				 s[i].put("subscription_retry__15_afn_fg", rs.getString("subscription_retry__15_afn_fg"));
				 s[i].put("subscription_retry__5_afn_fg", rs.getString("subscription_retry__5_afn_fg"));
				 s[i].put("subscription_retry__2_afn_fg", rs.getString("subscription_retry__2_afn_fg"));
				 s[i].put("retry_successfull__15_afn_fg", rs.getString("retry_successfull__15_afn_fg"));
				 s[i].put("retry_successfull__5_afn_fg", rs.getString("retry_successfull__5_afn_fg"));
				 s[i].put("retry_successfull__2_afn_fg", rs.getString("retry_successfull__2_afn_fg"));
				 s[i].put("total_subscription_revenue_fg", rs.getString("total_subscription_revenue_fg"));
				 s[i].put("total_resubscription_revenue_fg", rs.getString("total_resubscription_revenue_fg"));
				 s[i].put("subscription_requests_received__15_afn_fgr", rs.getString("subscription_requests_received__15_afn_fgr"));
				 s[i].put("subscription_requests_received__5_afn_fgr", rs.getString("subscription_requests_received__5_afn_fgr"));
				 s[i].put("subscription_requests_received__2_afn_fgr", rs.getString("subscription_requests_received__2_afn_fgr"));
				 s[i].put("successful_subscriptions__15_afn_fgr", rs.getString("successful_subscriptions__15_afn_fgr"));
				 s[i].put("successful_subscriptions__5_afn_fgr", rs.getString("successful_subscriptions__5_afn_fgr"));
				 s[i].put("successful_subscriptions__2_afn_fgr", rs.getString("successful_subscriptions__2_afn_fgr"));
				 s[i].put("subscription_retry__15_afn_fgr", rs.getString("subscription_retry__15_afn_fgr"));
				 s[i].put("subscription_retry__5_afn_fgr", rs.getString("subscription_retry__5_afn_fgr"));
				 s[i].put("subscription_retry__2_afn_fgr", rs.getString("subscription_retry__2_afn_fgr"));
				 s[i].put("retry_successfull__15_afn_fgr", rs.getString("retry_successfull__15_afn_fgr"));
				 s[i].put("retry_successfull__5_afn_fgr", rs.getString("retry_successfull__5_afn_fgr"));
				 s[i].put("retry_successfull__2_afn_fgr", rs.getString("retry_successfull__2_afn_fgr"));
				 s[i].put("total_subscription_revenue_fgr", rs.getString("total_subscription_revenue_fgr"));
				 s[i].put("total_resubscription_revenue_fgr", rs.getString("total_resubscription_revenue_fgr"));

				 s[i].put("total_subscription_requests_15_afn", rs.getString("total_subscription_requests_15_afn"));
				 s[i].put("total_subscription_requests_5_afn", rs.getString("total_subscription_requests_5_afn"));
				 s[i].put("total_subscription_requests_2_afn", rs.getString("total_subscription_requests_2_afn"));
				 s[i].put("total_subscription_successfull_15_afn", rs.getString("total_subscription_successfull_15_afn"));
				 s[i].put("total_subscription_successfull_5_afn", rs.getString("total_subscription_successfull_5_afn"));
				 s[i].put("total_subscription_successfull_2_afn", rs.getString("total_subscription_successfull_2_afn"));
				 s[i].put("total_subscription_successfull", rs.getString("total_subscription_successfull"));
				 
				 s[i].put("active_Base", rs.getString("active_Base"));
				 s[i].put("grace_Base", rs.getString("grace_Base"));
				 s[i].put("retry_base", rs.getString("retry_base"));
				 
				 s[i].put("cci", rs.getString("cci"));
				 s[i].put("sms", rs.getString("sms"));
				 s[i].put("ussd", rs.getString("ussd"));
				 s[i].put("voluntary_Churn", rs.getString("voluntary_Churn"));
				 s[i].put("involuntary_churn", rs.getString("involuntary_churn"));
				 s[i].put("total_churn", rs.getString("total_churn"));
				 
				 s[i].put("total_sub_req_rec_15", total_sub_req_rec_15);
				 s[i].put("total_sub_req_rec_5", total_sub_req_rec_5);
				 s[i].put("total_sub_req_rec_2", total_sub_req_rec_2);
				 s[i].put("total_sub_suc_15", total_sub_suc_15);
				 s[i].put("total_sub_suc_5", total_sub_suc_5);
				 s[i].put("total_sub_suc_2", total_sub_suc_2);
				 s[i].put("total_resub_req_rec_15", total_resub_req_rec_15);
				 s[i].put("total_resub_req_rec_5", total_resub_req_rec_5);
				 s[i].put("total_resub_req_rec_2", total_resub_req_rec_2);
				 s[i].put("total_resub_suc_15", total_resub_suc_15);
				 s[i].put("total_resub_suc_5", total_resub_suc_5);
				 s[i].put("total_resub_suc_2", total_resub_suc_2);
				 s[i].put("total_sub_revenue", total_sub_revenue);
				 s[i].put("total_resub_revenue", total_resub_revenue);
				 s[i].put("total_grand_revenue", rs.getString("total_grand_revenue"));
				 s[i].put("total_grand_subscription_revenue", rs.getString("total_grand_subscription_revenue"));
				 s[i].put("total_grand_resubscription_revenue", rs.getString("total_grand_resubscription_revenue"));
				 s[i].put("date_time", (rs.getString("date_time")).substring(0, 10));
				 
				 ++i;
			 }
		 } catch(Exception e) {
			 System.out.println("Exception in geting Value im MIS Bean.."+e);
			 e.printStackTrace();
		 } finally {
			 if(rs!= null) {
				 rs.close();
			 }
			 if(stmt != null)  {
				 stmt.close();
			 }
			 if(conn != null) {
				 conn.close();
			 }
		 }
		return s;		 
	 }
}